# Mini-Netflix Backend - Render Deploy

services:
  - type: web
    name: mini-netflix-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_HOST
        fromDatabase:
          name: mini-netflix-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: mini-netflix-db
          property: port
      - key: DB_USERNAME
        fromDatabase:
          name: mini-netflix-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mini-netflix-db
          property: password
      - key: DB_DATABASE
        fromDatabase:
          name: mini-netflix-db
          property: database
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h

  - type: pserv
    name: mini-netflix-db
    env: postgres
    plan: free
    databaseName: mini_netflix_db_y9kb
    databaseUser: mini_netflix_db_y9kb_user
